language: php

matrix:
  include:
    - php: 5.3.3
      env: DB=mysqli
    - php: 5.3
      env: DB=mysqli # MyISAM
    - php: 5.4
      env: DB=mysqli
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=mariadb
    - php: 5.4
      env: DB=postgres
    - php: 5.4
      env: DB=sqlite3
    - php: 5.4
      env: DB=mysqli;SLOWTESTS=1
    - php: 5.5
      env: DB=mysqli
    - php: 5.6
      env: DB=mysqli
    - php: 7.0
      env: DB=mysqli
    - php: hhvm
      env: DB=mysqli
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

services:
  - redis-server

install:
  - . travis/travis-install.sh

before_script:
  - . travis/travis-before-script.sh

script:
  - . travis/travis-script.sh
